spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${auth.db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${auth.db.username}
    password: ${auth.db.password}

eureka:
  client:
    service-url:
      defaultZone: ${eureka.server.url}

service:
  jwt:
    access-expiration: ${security.jwt.expiration}
    secret-key: ${security.jwt.key}

server:
  port: ${auth.server.port}