spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${order.db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${order.db.username}
    password: ${order.db.password}
  data:
    redis:
      host: ${order.redis.host}
      port: ${order.redis.port}
      username: ${order.redis.username}
      password: ${order.redis.password}

server:
  port: ${order.server.port}

eureka:
  client:
    service-url:
      defaultZone: ${eureka.server.url}

management:
  zipkin:
    tracing:
      endpoint: ${zipkin.url}
  tracing:
    sampling:
      probability: 1.0